In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('data/cars.csv')
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [4]:
df['brand'].nunique()

32

In [5]:
df['brand'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Fiat', 'Datsun', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Audi', 'Volkswagen', 'BMW',
       'Nissan', 'Lexus', 'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo',
       'Kia', 'Force', 'Ambassador', 'Ashok', 'Isuzu', 'Opel', 'Peugeot'],
      dtype=object)

In [6]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [7]:
df['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [8]:
df['fuel'].nunique()

4

In [9]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [10]:
df.owner.nunique()

5

In [11]:
df.owner.unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'], dtype=object)

In [12]:
df.owner.value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [13]:
df.shape

(8128, 5)

## 1. OneHotEncoding using Pandas

In [14]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

In [15]:
# Solving Multicolinearity problem (n-1)
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True,dtype=int)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

In [16]:
X=df.drop(columns=['selling_price'])
y=df['selling_price']

## 2. OneHotEncoding using Sklearn

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=45)

In [18]:
X_train.head()

        brand  km_driven    fuel         owner
5181  Renault      50000  Diesel   First Owner
2024     Tata      74000  Petrol  Second Owner
6203    Skoda      40000  Diesel   First Owner
7026     Tata      28000  Petrol  Second Owner
5837     Tata       5000  Petrol   First Owner

In [19]:
X_train.shape

(6502, 4)

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
#!pip install --upgrade scikit-learn --user

Requirement already satisfied: scikit-learn in c:\users\p\anaconda3\lib\site-packages (1.3.2)
Requirement already satisfied: scipy>=1.5.0 in c:\users\p\anaconda3\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\p\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: numpy<2.0,>=1.17.3 in c:\users\p\anaconda3\lib\site-packages (from scikit-learn) (1.24.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\p\anaconda3\lib\site-packages (from scikit-learn) (2.1.0)

In [22]:
ohe = OneHotEncoder(drop='first',sparse=False ,dtype=np.int32)
ohe

OneHotEncoder(drop='first', dtype=<class 'numpy.int32'>, sparse=False)

In [34]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

C:\Users\P\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [35]:
X_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0]])

In [36]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [37]:
X_test_new

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 0]])

In [25]:
X_train_new.shape

(6502, 7)

In [38]:
X_test_new.shape

(1626, 7)

In [40]:
X_train[['brand','km_driven']].values

array([['Renault', 50000],
       ['Tata', 74000],
       ['Skoda', 40000],
       ...,
       ['Hyundai', 76460],
       ['Volvo', 20000],
       ['Tata', 120000]], dtype=object)

In [41]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Renault', 50000, 1, ..., 0, 0, 0],
       ['Tata', 74000, 0, ..., 1, 0, 0],
       ['Skoda', 40000, 1, ..., 0, 0, 0],
       ...,
       ['Hyundai', 76460, 1, ..., 0, 0, 0],
       ['Volvo', 20000, 1, ..., 0, 0, 0],
       ['Tata', 120000, 1, ..., 1, 0, 0]], dtype=object)

In [42]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

## 3. OneHotEncoding with Top Categories

In [43]:
counts = df['brand'].value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [44]:
df['brand'].nunique()
threshold = 100

In [49]:
uncommon = counts[counts <= threshold].index

In [50]:
uncommon

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [47]:
len(repl)

20

In [62]:
pd.get_dummies((df['brand']),dtype=int).sample(5)

,Ambassador,Ashok,Audi,BMW,Chevrolet,Daewoo,Datsun,Fiat,Force,Ford,...,Mitsubishi,Nissan,Opel,Peugeot,Renault,Skoda,Tata,Toyota,Volkswagen,Volvo
4378,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7148,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
889,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1226,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3627,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [68]:
brand= pd.get_dummies(X_train['brand'].replace(uncommon, 'uncommon'),dtype=int)

In [69]:
brand.shape

(6502, 13)

In [77]:
brand_test= pd.get_dummies(X_test['brand'].replace(uncommon, 'uncommon'),dtype=int)

In [73]:
brand_ohe=np.hstack((X_train[['km_driven']].values,X_train_new,brand)).shape

In [75]:
brand_ohe

(6502, 21)

In [78]:
brand_ohe_test=np.hstack((X_test[['km_driven']].values,X_test_new,brand_test)).shape

In [79]:
brand_ohe_test

(1626, 21)